### ISSUE TITLE
cvManovaCore contrast error

### ISSUE THREAD

**Issue by verve9** [allefeld/cvmanova#27]
Hi,

I have 16 conditions and I set up 1 main effect and 1 interaction effect contrasts

_% set up contrasts
Cs = {};
% 1) main effect of threat
Cs{1} = [ -1 1  -1  1  0  0  0  0 0  0  0  0 0  0  0  0]';
% 2) interaction
Cs{2} = [ -1 1  1  -1 0  0  0  0 0  0  0  0 0  0  0  0]';_

and I ran cvManovaSearchlight,

_cvManovaSearchlight(dir, 3, Cs)_

but I had error message as follows,

_computing cross-validated MANOVA on searchlight
Error using cvManovaCore (line 82)
contrast 1 is not estimable in session 1!

Error in runSearchlight (line 73)
res = fun(nan(0, 1), varargin{:});

Error in cvManovaSearchlight (line 69)
[D, p] = runSearchlight(['cmsCheckpoint' uid
'.mat'], slRadius, mask, ..._

Can you help me to handle with this?  Thanks.

**Comment by allefeld** [comment]
Can you describe the 16 conditions? Looks like you have a 2 × 2 design, but then another 12 conditions?

And can you send me the SPM.mat file?

**Comment by verve9** [comment]
SPM.mat
<https://drive.google.com/file/d/1C4aeBbT0TlKX-h4unXUBW4rR-Z_B7088/view?usp=drive_web>
Hi Carsten,

I have 16 conditions as follows,

% Fake-Negative-Safe
% Fake-Negative-Threat
% Fake-Positive-Safe
% Fake-Positive-Threat
% Real-Negative-Safe
% Real-Negative-Threat
% Real-Positive-Safe
% Real-Positive-Threat
% rate  Fake-Negative-Safe
% rate  Fake-Negative-Threat
% rate  Fake-Positive-Safe
% rate  Fake-Positive-Threat
% rate  Real-Negative-Safe
% rate  Real-Negative-Threat
% rate  Real-Positive-Safe
% rate  Real-Positive-Threat

and our interests are only the first 4, not reals and not ratings.

My first contrast was safe vs. threat so
*Cs{1} = [ -1 1 -1 1 0 0 0 0 0 0 0 0 0 0 0 0]';*

and second contrast was interaction between emotion and threat,

*Cs{2} = [ -1 1 1 -1 0 0 0 0 0 0 0 0 0 0 0 0]';*
I am attaching SPM.mat. I did not input condition labels as above.
Condition names should be 'datapoint1~16' in SPM.mat.

Thanks,

**Comment by allefeld** [comment]
Thanks!

The problem is that not all conditions are present in all sessions
session 1 is missing 1 2, 5 6, 9 10, 13 14
session 2 is  missing 3 4, 7 8, 11 12, 15 16
and the same alternating in the other sessions.

If a contrast involves a condition which is not present in a session, then that contrast cannot be estimated, and since cvMANOVA uses leave-one-session-out cross-validation, it doesn't work.

What you could do is try to join session 1 & 2, 3 & 4, and 5 & 6 into 3 new sessions.

Option 1: Join while setting up the model in SPM. But that has the disadvantage that HRF convolution, estimation of serial correlations etc. cross actual session boundaries.

Option 2: Hack cvManovaSearchlight.m, after the line where the data are loaded (line 47 in the current version):
– `Ys` is a cell array of per-session preprocessed fMRI data. Concatenate the contents of the respective cells vertically, e.g. using `[ ; ]`.
– `Xs` is a cell array of per-session preprocessed design matrices. Concatenate the contents of the respective cells diagonally, using `blkdiag`.
– `misc.fE` is a vector of per-session error degrees of freedom. Add the numbers in the respective elements.
After that, `Ys`, `Xs`, and `misc.fE` should each have 3 elements corresponding to the new 3 sessions.

Option 1 is easier, but option 2 is cleaner.

I hope this helps?

**Comment by allefeld** [comment]
PS: Unrelated, I would also recommend to include estimated motion correction parameters as confound regressors.

**Comment by verve9** [comment]
I followed your Option 2, and I encountered another error message when I run line 69-70 in cvManovaSearchlight.m. 
Seems that I also have to hack cvManova somewhere? Can you please help?

>> [D, p] = runSearchlight(['cmsCheckpoint' uid '.mat'], slRadius, mask, ...
    @cvManovaCore, Ys, Xs, Cs, misc.fE, permute, lambda);
Error using cvManovaCore (line 69)
inconsistent number of scans between data and design!

Error in runSearchlight (line 73)
res = fun(nan(0, 1), varargin{:});

**Comment by allefeld** [comment]
Can you show me the code you added to cvManovaSearchlight?

**Comment by verve9** [comment]
Yss{1}=[Ys{1}; Ys{2}];
Yss{2}=[Ys{3}; Ys{4}];
Yss{3}=[Ys{5}; Ys{6}];
Ys=Yss; clearvars Yss;

Xss{1,1}=blkdiag(Xs{1},Xs{2});
Xss{2,1}=blkdiag(Xs{3},Xs{4});
Xss{3,1}=blkdiag(Xs{5},Xs{6});
Xs=Xss; clearvars Xss;

qq(1,1)=sum(misc.fE(1:2));
qq(2,1)=sum(misc.fE(3:4));
qq(3,1)=sum(misc.fE(5:6));
misc = rmfield(misc,'fE');
misc.fE=qq; clearvars qq;

**Comment by allefeld** [comment]
OK, that looks right.

Before the added code, use `save` to save the complete local workspace and send me the file, please.

**Comment by verve9** [comment]
matlab.mat
<https://drive.google.com/file/d/1d_ZQu0jJRxt2IaRHWapj5aGjqS3kok4Q/view?usp=drive_web>
Hello, I am attaching local workspace before running the added code above.
(Ys, Xs, and misc.fE has 6 elements for now.)

**Comment by allefeld** [comment]
The problem is that you construct `Yss` using a single index, which produces a cell array of size 1x3, but you construct `Xss` using two indices, producing a cell array of size 3x1. Because of that, `cvManovaCore` thinks that data and design do not match each other.

Try:
```
Yss{1,1}=[Ys{1}; Ys{2}];
Yss{2,1}=[Ys{3}; Ys{4}];
Yss{3,1}=[Ys{5}; Ys{6}];
Ys=Yss; clearvars Yss;
```

Note that because the first two conditions are only present in the even appended run, they correspond now to regressors  18 and 19. E.g. your main effect contrast has to be
```
Cs = [0 0 -1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 -1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]'
```

**Comment by verve9** [comment]
Thank you! I made a silly mistake.

For the contrasts, you mean "17 and 18", not "18 and 19", right? (I have 16 conditions total, so condition 1 and 2 in the second should be condition 17, 18 I guess).
So new main and interaction effect contrasts should be like,

% 1) main effect of threat
Cs{1} = [[0;0;-1;1;0;0;0;0;0;0;0;0;0;0;0;0;-1;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0]]';
% 2) interaction
Cs{2} = [[0;0;1;-1;0;0;0;0;0;0;0;0;0;0;0;0;-1;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0]]';

Is this correct?

**Comment by allefeld** [comment]
No, it is 18 and 19, because in the internal format (`Xs`), the constant regressor is added. You therefore have 16 + 1 regressors in session 1, session 2 regressors start at 18.

**Comment by allefeld** [comment]
I think this issue is resolved? If not, feel free to re-open.

**Comment by verve9** [comment]
Hi,

I have another issue with cvManovaRegion. The issue is that this works well with some ROI mask, but does not work with some other ROI masks. In my case, I created three ROI region masks, (cell array of  3D volumes of 1 and 0). ROI 1 and 2 have some overlappings and ROI 3 is union of ROIs 1 and 2. The problem is that cvManovaRegion works only for ROI 2, but and ROI 1 and 3, and the error message is that,

data insufficient for the 1259 voxels of region 1!
data insufficient for the 1526 voxels of region 3!

Can you please help? Thanks.
